# Generated by Django 3.2.3 on 2021-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
