# Generated by Django 3.2.3 on 2021-06-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.quiz'),
        ),
    ]
