# Generated by Django 3.2.3 on 2021-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
