# Generated by Django 3.2.3 on 2021-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210603_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='url',
        ),
        migrations.AddField(
            model_name='module',
            name='module',
            field=models.FileField(default=1, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
